### ISSUE TITLE
How show dialog message before load the DLLs?

### ISSUE THREAD

**Issue by lwmirkk** [domgho/innodependencyinstaller#45]
In some systems, the DLL load and checks take up to 1 minute and in this time, the setup is invisible.
I want to show a message to the user like : "wait, checking required dependencies..."

It is possible?

Thanks a lot.

**Comment by kungfux** [comment]
When dependencies are being downloaded and installed the appropriate setup wizard step displays, e.g. 

![image](https://user-images.githubusercontent.com/10548881/74092319-1b9c3b80-4ad3-11ea-8d07-111cc10cdfb5.png)

![image](https://user-images.githubusercontent.com/10548881/74092303-fdced680-4ad2-11ea-80ed-686f2fc45f33.png)

So, I'm not quite sure what the issue you are pointing to.

What you may try is to hack `function NextButtonClick(CurPageID: Integer): boolean;` in `products.pas` file to show the message box to the user to aware him that setup may disappear for a while by calling `MsgBox` pascal function as following:

```
function NextButtonClick(CurPageID: Integer): boolean;
{
	At each "next" button click
	See: http://www.jrsoftware.org/ishelp/index.php?topic=scriptevents
}
begin
	Result := true;
	
	

	if CurPageID = wpReady then begin
	
		MsgBox('Setup will download files over internet and may disappear for a while, please wait...', mbInformation, MB_OK);
...
```

![image](https://user-images.githubusercontent.com/10548881/74092604-85b6df80-4ad7-11ea-8278-7a8f0d5e6ab5.png)


Hope this helps. If not, please describe your issue more.

Good luck.

**Comment by lwmirkk** [comment]
@kungfux thanks for the reply.

Today when the user open the setup file, this take up to 1 minute (in some systems) to show the first dialog with what to download and install.

Checking the debug, this time is taken most by the isxdl.dll extract and load.
See this picture with timestamps:
![isxdl](https://user-images.githubusercontent.com/36115546/74102487-8cb70f80-4b22-11ea-8529-c03204bd3498.jpg)

So, in this system, the DLL load take 14 sec. In this time, the setup not show anything.
I made some tests and the problem was with the **SolidCompression** enabled.

So, now there is no more waiting time, thanks a lot. =)

**Comment by kungfux** [comment]
I got it. Good job, @lwmirkk! Thanks for sharing the solution.
