### ISSUE TITLE
Why are use_dotnetfx46+ allowing .NET Framework 4.5.0 as min-version?

### ISSUE THREAD

**Issue by pekspro** [domgho/innodependencyinstaller#46]
In setup.iss, I see these lines:

    #ifdef use_dotnetfx45
	    dotnetfx45(50); // min allowed version is 4.5.0
    #endif

    #ifdef use_dotnetfx46
	    dotnetfx46(50); // min allowed version is 4.5.0
    #endif

    #ifdef use_dotnetfx47
	    dotnetfx47(50); // min allowed version is 4.5.0
    #endif

    #ifdef use_dotnetfx48
	    dotnetfx48(50); // min allowed version is 4.5.0
    #endif

It looks to me that if I define that .NET Framework 4.6 or latest is required, the framework will not be updated if version 4.5.0 is installed. I did some quick test, and this seems to be the case. Is this by purpose? Looks like a copy and paste error to me.

**Comment by pekspro** [comment]
Thanks for a very fast and useful answer :-) This was the information I needed to solve my scenario.

By the way, I think this is a really nice project.

**Comment by domgho** [comment]
Exactly, it's just an example to show it's possible
