### ISSUE TITLE
Where does isxdl.dll come from?

### ISSUE THREAD

**Issue by mlaily** [domgho/InnoDependencyInstaller#54]
A key piece of the whole project is the `isxdl.dll` library, but I can't find the source anywhere.

I think it's important we — users of this project — can rebuild it ourselves:
- We need to be certain it does not contain malicious code without having to rely only on your good will.
- Having the whole source code is a guarantee the project won't die if something requires this part to be rebuilt some day.

Could you please link to it, or include it somewhere?

Thanks.

**Comment by domgho** [comment]
https://sourceforge.net/p/istool/code/HEAD/tree/

**Comment by mlaily** [comment]
Thank you.

Would you be interested in a PR to add this link in a read-me somewhere in the project?

**Comment by kungfux** [comment]
@mlaily [Project-structure](https://github.com/domgho/InnoDependencyInstaller/wiki/Project-structure) wiki page has been updated to point users to the downloader's dll source code. Thanks!
